#-*- coding: utf-8 -*-
CPSTOCKCODE_CODE = 0
CPSTOCKCODE_NAME = 1

CPSTOCKMST_INDUSTRY_CODE = 2
CPSTOCKMST_CATEGORY = 5 
CPSTOCKMST_PER = 28
CPSTOCKMST_BPS = 70


CPSTOCKCHART_REQ_CODE = 0
CPSTOCKCHART_REQ_DATE_OR_COUNT = 1

CPSTOCKCHART_REQ_PARAM_DATE = ord('1')
CPSTOCKCHART_REQ_PARAM_COUNT = ord('2')

CPSTOCKCHART_REQ_END_DATE = 2
CPSTOCKCHART_REQ_START_DATE = 3

CPSTOCKCHART_REQ_COUNT = 4

CPSTOCKCHART_REQ_FIELD = 5

CPSTOCKCHART_REQ_PARAM_FIELD_DATE = 0
CPSTOCKCHART_REQ_PARAM_FIELD_TIME = 1
CPSTOCKCHART_REQ_PARAM_FIELD_OPEN = 2
CPSTOCKCHART_REQ_PARAM_FIELD_HIGH = 3
CPSTOCKCHART_REQ_PARAM_FIELD_LOW = 4
CPSTOCKCHART_REQ_PARAM_FIELD_CLOSE = 5
CPSTOCKCHART_REQ_PARAM_FIELD_VOLUME = 8

CPSTOCKCHART_REQ_TYPE = 6
CPSTOCKCHART_REQ_TYPE_PARAM_DAY = ord('D')
CPSTOCKCHART_REQ_TYPE_PARAM_WEEK = ord('W')
CPSTOCKCHART_REQ_TYPE_PARAM_MONTH = ord('M')
CPSTOCKCHART_REQ_TYPE_PARAM_MIN = ord('m')
CPSTOCKCHART_REQ_TYPE_PARAM_TICK = ord('T')

CPSTOCKCHART_REQ_ADJ = 9
CPSTOCKCHART_REQ_ADJ_PARAM_DEFAULT = ord('0')
CPSTOCKCHART_REQ_ADJ_PARAM_ADJUST = ord('1')

CPSTOCKCHART_RES_DATA_COUNT = 3 

CPTD6033_ACCOUNT_NAME = 0						#계좌명
CPTD6033_PAYMENT_STOCK_COUNT = 1				#결제 잔고 수량
CPTD6033_CONCLUSION_STOCK_COUNT = 2				#체결 잔고 수량
CPTD6033_ASSESSED_VALUE = 3						#평가금액
CPTD6033_VALUATION = 5							#평가손익
CPTD6033_REVENUE_RATIO = 8						#수익률

CPTD6033_RECEIVE_COUNT = 7						#종목 수신 개수

CPTD6033_PARAMETER_GOOD_CODE_STOCK = "01"		#상품 코드 주식
CPTD6033_PARAMETER_ACCOUNT_NUM = 0				#계좌번호 입력
CPTD6033_PARAMETER_GOOD_CODE = 1				#삼품 코드

CPTD6044_GETDATA_NAME = 0				    	#종목명
CPTD6044_GETDATA_CODE = 12    			        #종목코드
CPTD6044_GETDATA_PAYMENT_STOCK_COUNT = 7		#체결잔고수량
CPTD6044_GETDATA_SELL_COUNT = 15				#매도가능수량
CPTD6044_GETDATA_ASSESSED_VALUE = 9				#평가금액
CPTD6044_GETDATA_VALUATION = 10			    	#평가손익
CPTD6044_GETDATA_PRICE = 18				        #손익단가


CPTD0311_INPUT_ORDER            = 0
CPTD0311_INPUT_ACCOUNT_NUM      = 1
CPTD0311_INPUT_GOOD_CODE        = 2  
CPTD0311_INPUT_STOCK_CODE       = 3
CPTD0311_INPUT_STOCK_COUNT      = 4
CPTD0311_INPUT_STOCK_PRICE      = 5

CPTD0311_PARAM_ORDER_BUY        = 2
CPTD0311_PARAM_ORDER_SELL       = 1
CPTD0311_PARAM_GOOD_STOCK       = "01"



CPTD6044_GETDATA_STOCK_NAME = 0					#매도 가능 수량
CPTD6044_GETDATA_STOCK_NAME = 0					#손익 단가



