#-*- coding: utf-8 -*-
CPSTOCKCODE_CODE = 0
CPSTOCKCODE_NAME = 1


CPSTOCKMST_CATEGORY = 5 


CPSTOCKCHART_REQ_CODE = 0
CPSTOCKCHART_REQ_DATE_OR_COUNT = 1

CPSTOCKCHART_REQ_PARAM_DATE = ord('1')
CPSTOCKCHART_REQ_PARAM_COUNT = ord('2')

CPSTOCKCHART_REQ_END_DATE = 2
CPSTOCKCHART_REQ_START_DATE = 3

CPSTOCKCHART_REQ_COUNT = 4

CPSTOCKCHART_REQ_FIELD = 5

CPSTOCKCHART_REQ_PARAM_FIELD_DATE = 0
CPSTOCKCHART_REQ_PARAM_FIELD_TIME = 1
CPSTOCKCHART_REQ_PARAM_FIELD_OPEN = 2
CPSTOCKCHART_REQ_PARAM_FIELD_HIGH = 3
CPSTOCKCHART_REQ_PARAM_FIELD_LOW = 4
CPSTOCKCHART_REQ_PARAM_FIELD_CLOSE = 5
CPSTOCKCHART_REQ_PARAM_FIELD_VOLUME = 8

CPSTOCKCHART_REQ_TYPE = 6
CPSTOCKCHART_REQ_TYPE_PARAM_DAY = ord('D')
CPSTOCKCHART_REQ_TYPE_PARAM_WEEK = ord('W')
CPSTOCKCHART_REQ_TYPE_PARAM_MONTH = ord('M')
CPSTOCKCHART_REQ_TYPE_PARAM_MIN = ord('m')
CPSTOCKCHART_REQ_TYPE_PARAM_TICK = ord('T')

CPSTOCKCHART_REQ_ADJ = 9
CPSTOCKCHART_REQ_ADJ_PARAM_DEFAULT = ord('0')
CPSTOCKCHART_REQ_ADJ_PARAM_ADJUST = ord('1')

CPSTOCKCHART_RES_DATA_COUNT = 3 